title: PNP Marketplace | Plug & Play Germany GmbH
email: marketing-ger@pnptc.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: startupautobahn
# github_username:  jekyll

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - airtable

collections:
  - products

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
